export const loveinterests =[
    {
        name: "Torrent",
        affectionlvl: 100,
        img: "./pics/torrent.png",
        route: "",
        gender: "Male",
        maplocation: "Always with you",
    },
    {
        name: "Melina",
        affectionlvl: 50,
        img: "./pics/melina.png",
        route: "",
        gender: "Female",
        maplocation: "The Table of Lost Grace",
    },
    {
        name: "Blaidd",
        affectionlvl: 30,
        img: "./pics/blaidd.png",
        route: "",
        gender: "Male",
        maplocation: "Siofra River, Mistwood Ruins",
    },
    {
        name: "Ranni the Witch",
        affectionlvl: 50,
        img: "./pics/ranni.png",
        route: "",
        gender: "Female",
        maplocation: "Three Sisters, Caria Manor",
    },
    {
        name: "Patches",
        affectionlvl: 10,
        img: "./pics/patches.png",
        route: "",
        gender: "Male",
        maplocation: "Murkwater Cave, Roundtable Hold",
    },
    {
        name: "Varré",
        affectionlvl: 50,
        img: "./pics/varre.png",
        route: "",
        gender: "Male",
        maplocation: "Limgrave, Roundtable Hold",
    },
    {
        name: "Fia",
        affectionlvl: 50,
        img: "./pics/fia.png",
        route: "",
        gender: "Female",
        maplocation: "Roundtable Hold, Deeproot Depths",
    },
    {
        name: "Godrick the Grafted",
        affectionlvl: 0,
        img: "./pics/godrick.png",
        route: "",
        gender: "Male",
        maplocation: "Stormveil Castle",
    },
    {
        name: "Radahn, Starscourge",
        affectionlvl: 0,
        img: "./pics/radahn.png",
        route: "",
        gender: "Male",
        maplocation: "Caelid, Redmane Castle",
    },
    {
        name: "Rykard, Lord of Blasphemy",
        affectionlvl: 0,
        img: "./pics/rykard.png",
        route: "",
        gender: "Male",
        maplocation: "Volcano Manor",
    },
    {
        name: "Malenia, Blade of Miquella",
        affectionlvl: 0,
        img: "./pics/malenia.png",
        route: "",
        gender: "Female",
        maplocation: "Elphael, Brace of the Haligtree",
    },
    {
        name: "Miquella",
        affectionlvl: 0,
        img: "./pics/miquella.png",
        route: "",
        gender: "Femboy",
        maplocation: "Haligtree, in his dream form",
    },
    {
        name: "Mohg, Lord of Blood",
        affectionlvl: 0,
        img: "./pics/mohg.png",
        route: "",
        gender: "Male",
        maplocation: "Mohgwyn Palace",
    },
    {
        name: "Commander Niall",
        affectionlvl: 0,
        img: "./pics/niall.png",
        route: "",
        gender: "Male",
        maplocation: "Castle Sol",
    },
    {
        name: "Sir Gideon Ofnir",
        affectionlvl: 20,
        img: "./pics/gideon.png",
        route: "",
        gender: "Male",
        maplocation: "Roundtable Hold",
    },
    {
        name: "Ensha of the Royal Remains",
        affectionlvl: 30,
        img: "./pics/ensha.png",
        route: "",
        gender: "Male",
        maplocation: "Roundtable Hold",
    },
    {
        name: "Nepheli Loux",
        affectionlvl: 50,
        img: "./pics/nepheli.png",
        route: "",
        gender: "Female",
        maplocation: "Stormveil Castle",
    },
    {
        name: "Hyetta",
        affectionlvl: 50,
        img: "./pics/hyetta.png",
        route: "",
        gender: "Female",
        maplocation: "Lake of Liurnia",
    },
    {
        name: "D, Hunter of the Dead",
        affectionlvl: 45,
        img: "./pics/d.png",
        route: "",
        gender: "Male",
        maplocation: "Roundtable Hold, Altus Plateau",
    },
    {
        name: "Gurranq, Beast Roar",
        affectionlvl: 30,
        img: "./pics/gurranq.png",
        route: "",
        gender: "Male",
        maplocation: "Bestial Sanctum, Caelid",
    },
    {
        name: "Roderika",
        affectionlvl: 50,
        img: "./pics/roderika.png",
        route: "",
        gender: "Female",
        maplocation: "Stormveil Castle, Roundtable Hold",
    },
    {
        name: "Tanith",
        affectionlvl: 50,
        img: "./pics/tanith.png",
        route: "",
        gender: "Female",
        maplocation: "Volcano Manor",
    },
    {
        name: "Blackguard Big Boggart",
        affectionlvl: 20,
        img: "./pics/boggart.png",
        route: "",
        gender: "Male",
        maplocation: "Liurnia of the Lakes",
    },
    {
        name: "Hoarah Loux",
        affectionlvl: 0,
        img: "./pics/hoarahloux.png",
        route: "",
        gender: "Male",
        maplocation: "Leyndell, Royal Capital",
    },
    {
        name: "Giant Godskin Apostle",
        affectionlvl: 0,
        img: "./pics/godskinapostle.png",
        route: "",
        gender: "Male",
        maplocation: "Forbidden Lands",
    },
    {
        name: "The Three Fingers",
        affectionlvl: 0,
        img: "./pics/3fingers.png",
        route: "",
        gender: "Male",
        maplocation: "Royal Capital Sewers",
    },
    {
        name: "Shabiri",
        affectionlvl: 0,
        img: "./pics/shabiri.png",
        route: "",
        gender: "Male",
        maplocation: "Subterranean Shunning-Grounds",
    },
    {
        name: "Elden Beast",
        affectionlvl: 0,
        img: "./pics/eldenbeast.png",
        route: "",
        gender: "Male",
        maplocation: "Erdtree",
    },
    {
        name: "Radagon of the Golden Order",
        affectionlvl: 0,
        img: "./pics/radagon.png",
        route: "",
        gender: "Male",
        maplocation: "Erdtree",
    },
    {
        name: "Iron Fist Alexander",
        affectionlvl: 55,
        img: "./pics/alex.png",
        route: "",
        gender: "Male",
        maplocation: "Caelid, Redmane Castle",
    },
    {
        name: "Queen Marika, The Eternal",
        affectionlvl: 0,
        img: "./pics/marika.png",
        route: "",
        gender: "Female",
        maplocation: "Erdtree",
    },
    {
        name: "Morgott, The Omen King",
        affectionlvl: -50,
        img: "./pics/morgott.png",
        route: "",
        gender: "Male",
        maplocation: "Leyndell, Royal Capital",
    },
    {
        name: "Rennala, Queen of The Full Moon",
        affectionlvl: 20,
        img: "./pics/rennala.png",
        route: "",
        gender: "Female",
        maplocation: "Academy of Raya Lucaria ",
    },
    {
        name: "Royal Knight Loretta",
        affectionlvl: 0,
        img: "./pics/loretta.png",
        route: "",
        gender: "Female",
        maplocation: "Caria Manor",
    },
    {
        name: "Maliketh, The Black Blade",
        affectionlvl: 0,
        img: "./pics/maliketh.png",
        route: "",
        gender: "Male",
        maplocation: "Crumbling Farum Azula",
    },
    {
        name: "Dragonlord Placidusax",
        affectionlvl: 0,
        img: "./pics/placidusax.png",
        route: "",
        gender: "Male",
        maplocation: "Crumbling Farum Azula",
    },
    {
        name: "Fire Giant",
        affectionlvl: 0,
        img: "./pics/firegiant.png",
        route: "",
        gender: "Male",
        maplocation: "Mountaintops of The Giants",
    },
    {
        name: "Lichdragon Fortissax",
        affectionlvl: 0,
        img: "./pics/fortissax.png",
        route: "",
        gender: "Non-Binary",
        maplocation: "Deeproot Depths",
    },
    {
        name: "Draconic Tree Sentinel",
        affectionlvl: 0,
        img: "./pics/draconitreesentinel.png",
        route: "",
        gender: "Male",
        maplocation: "Leyndell, Royal Capital",
    },
    {
        name: "Tree Sentinel",
        affectionlvl: -20,
        img: "./pics/treesentinel.png",
        route: "",
        gender: "Male",
        maplocation: "Limgrave",
    },
    {
        name: "Astel, Naturalborn of The Void",
        affectionlvl: 0,
        img: "./pics/astel.png",
        route: "",
        gender: "Male",
        maplocation: "Lake of Rot",
    },
    {
        name: "Sorceress Sellen",
        affectionlvl: 0,
        img: "./pics/sellen.png",
        route: "",
        gender: "Female",
        maplocation: "Waypoint Ruins",
    },
    {
        name: "Irina",
        affectionlvl: 0,
        img: "./pics/irina.png",
        route: "",
        gender: "Female",
        maplocation: "Weeping Penisula",
    },
    {
        name: "Rya",
        affectionlvl: 0,
        img: "./pics/rya.png",
        route: "",
        gender: "Female",
        maplocation: "Volcano Manor",
    },
    {
        name: "Enia",
        affectionlvl: 30,
        img: "./pics/enia.png",
        route: "",
        gender: "Female",
        maplocation: "Roundtable Hold",
    },
    {
        name: "Millicent",
        affectionlvl: 50,
        img: "./pics/millicent.png",
        route: "",
        gender: "Female",
        maplocation: "Church of The Plague",
    },
    {
        name: "Miriel, Pastor of Vows",
        affectionlvl: 0,
        img: "./pics/miriel.png",
        route: "",
        gender: "Male",
        maplocation: "Church of Vows",
    },
    {
        name: "Boc",
        affectionlvl: 40,
        img: "./pics/boc.png",
        route: "",
        gender: "Male",
        maplocation: "Limgrave",
    },
    {
        name: "Godwyn, Prince of Death",
        affectionlvl: 100,
        img: "./pics/godwyn.png",
        route: "",
        gender: "Male",
        maplocation: "Deeproot Depths",
    },
    {
        name: "Adan, The Thief Fire",
        affectionlvl: 0,
        img: "./pics/adan.png",
        route: "",
        gender: "Male",
        maplocation: "The Malefactor's Evergaol",
    },
    {
        name: "Bols, Carian Knight",
        affectionlvl: 0,
        img: "./pics/bols.png",
        route: "",
        gender: "Male",
        maplocation: "Cuckoo's Evergaols",
    },
    {
        name: "Seluvis",
        affectionlvl: 30,
        img: "./pics/seluvis.png",
        route: "",
        gender: "Male",
        maplocation: "Seluvis's Rise",
    },
    {
        name: "Merchant Kalé",
        affectionlvl: 30,
        img: "./pics/kale.png",
        route: "",
        gender: "Male",
        maplocation: "Church of Elleh",
    },
    {
        name: "Smithing Master Hewg",
        affectionlvl: 0,
        img: "./pics/hewg.png",
        route: "",
        gender: "Male",
        maplocation: "Roundtable Hold",
    },
    {
        name: "Thops",
        affectionlvl: 0,
        img: "./pics/thops.png",
        route: "",
        gender: "Male",
        maplocation: "Church of Irith",
    },
    {
        name: "Edgar",
        affectionlvl: -10,
        img: "./pics/edgar.png",
        route: "",
        gender: "Male",
        maplocation: "Castle Morne",
    },
    {
        name: "Rogier",
        affectionlvl: 0,
        img: "./pics/rogier.png",
        route: "",
        gender: "Male",
        maplocation: "Stormveil Castle",
    },
    {
        name: "War Counselor Iji",
        affectionlvl: 0,
        img: "./pics/iji.png",
        route: "",
        gender: "Male",
        maplocation: "Kingsrealm Ruins",
    },
    {
        name: "Banished Knight",
        affectionlvl: 0,
        img: "./pics/banishedknight.png",
        route: "",
        gender: "Male",
        maplocation: "Castle Sol",
    },

]
